"""Optional Airflow DAG stub exporter (import-guarded; Airflow not required).

Writes an *illustrative* DAG Python file that mirrors this demo's
train → validate → register step names. The stub is **not** runnable without
Airflow installed, and the happy path of this repo never imports ``airflow``.

Aligns with Metaflow's optional Airflow scheduling story:
https://docs.metaflow.org/production/scheduling-metaflow-flows/scheduling-with-airflow
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

# Default step graph matching build_pipeline()
DEFAULT_STEPS: tuple[str, ...] = ("train", "validate", "register")

_STUB_TEMPLATE = '''\
"""ILLUSTRATIVE Airflow DAG stub — NOT executed by this OSS demo.

Generated by ml-pipeline-metaflow-demo ``export_airflow_stub``.
Mirrors the toy step graph: {steps_arrow}

Honesty:
- This file is a teaching skeleton for teams that already run Airflow.
- Metaflow docs recommend Airflow mainly if you already operate Airflow;
  nested foreach / some newer step types are not supported there.
- The demo happy path stays Metaflow-/Airflow-free (thin custom DAG runner).
- Do not treat this as a production deploy artifact.

See: https://docs.metaflow.org/production/scheduling-metaflow-flows/scheduling-with-airflow
"""

from __future__ import annotations

# Import-guarded: importing this module without Airflow must not crash the demo.
try:
    from airflow import DAG  # type: ignore
    from airflow.operators.python import PythonOperator  # type: ignore
    from datetime import datetime, timedelta

    _AIRFLOW_AVAILABLE = True
except ImportError:  # pragma: no cover - exercised when Airflow absent
    DAG = None  # type: ignore
    PythonOperator = None  # type: ignore
    _AIRFLOW_AVAILABLE = False


def _noop_train(**_ctx):
    """Stub — wire to real train in a real deployment."""
    print("stub train")


def _noop_validate(**_ctx):
    print("stub validate (multi-metric gates)")


def _noop_register(**_ctx):
    print("stub register (lineage + candidate tag)")


_STEP_CALLABLES = {{
    "train": _noop_train,
    "validate": _noop_validate,
    "register": _noop_register,
}}

if _AIRFLOW_AVAILABLE:
    default_args = {{
        "owner": "vk-ai-demo",
        "depends_on_past": False,
        "retries": 0,
        "retry_delay": timedelta(minutes=1),
    }}
    with DAG(
        dag_id="{dag_id}",
        description="Illustrative stub mirroring ml-pipeline-metaflow-demo steps",
        default_args=default_args,
        start_date=datetime(2026, 1, 1),
        schedule=None,  # manual / external trigger in real setups
        catchup=False,
        tags=["oss-learning", "metaflow-demo-stub"],
    ) as dag:
{task_block}
else:
    dag = None  # Airflow not installed — stub is documentation only
'''


def _task_block(steps: Sequence[str]) -> str:
    lines: list[str] = []
    prev = None
    for name in steps:
        var = f"t_{name}"
        fn = "_STEP_CALLABLES.get(%r, _noop_train)" % name
        lines.append(
            f'        {var} = PythonOperator(task_id="{name}", python_callable={fn})'
        )
        if prev is not None:
            lines.append(f"        {prev} >> {var}")
        prev = var
    return "\n".join(lines) if lines else "        pass"


def export_airflow_stub(
    path: str | Path,
    *,
    steps: Sequence[str] | None = None,
    dag_id: str = "ml_train_validate_register_stub",
) -> Path:
    """Write an import-guarded Airflow DAG skeleton to ``path``."""
    step_list = tuple(steps) if steps is not None else DEFAULT_STEPS
    if not step_list:
        raise ValueError("steps must be non-empty")
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = _STUB_TEMPLATE.format(
        steps_arrow=" → ".join(step_list),
        dag_id=dag_id,
        task_block=_task_block(step_list),
    )
    out.write_text(text, encoding="utf-8")
    return out


def airflow_available() -> bool:
    """True only if ``airflow`` can be imported (optional extra — never required)."""
    try:
        import airflow  # noqa: F401

        return True
    except ImportError:
        return False
